React Capstone Project
MacCrazyman/stock-capstone pull request #3
Opened 2022-02-04 03:18 UTC by MacCrazyman

# React Capstone project ⚛️ 

## This PR contains all the features of the React capstone project:

* Use Financial Modeling API to get information.
* Use react to create front-end components.
* User Redux to store the information retrieved from the API.
* Styling made using Tailwind CSS.
* Webpage deployed using Heroku.
* Explanatory [video](https://drive.google.com/file/d/1tu6x65IFPv1Dd-NZyDcdi3JUgugpPrqK/view?usp=sharing)

2022-02-04 06:09 UTC, Meltrust requested changes
Hi @MacCrazyman, 

## Your project and design are so beautiful it's like a dream!  Good job so far!!  Please, checkout my comments below so we can get ready for approval 👇 


Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!



## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- [ ] OPTIONAL: I highly recommend you to put your Redux store inside your Redux folder.
- [ ] OPTIONAL: I highly recommend you use the duck's design folder structure for your Redux folder.  Look at this [article](https://medium.com/@matthew.holman/what-is-redux-ducks-46bcb1ad04b7).

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-04 06:09 UTC, Meltrust commented on README.md
> +[Live Demo Link](https://stock-capstone.herokuapp.com/)
- [x] For some reason, Heroku throws this error:

![image](https://user-images.githubusercontent.com/57421823/152475670-7a6885fa-55ab-4977-a8ef-10295e2f4b2a.png)

Please, kindly correct your deployment in order to meet this requirement.

2022-02-04 06:09 UTC, Meltrust commented on README.md
> +[Live Demo Link](https://stock-capstone.herokuapp.com/)
- [x] Please, add a link to your video on your readme file.  Make sure it does not reach the 5 minutes limit.

That way, your project will be well documented.

2022-02-04 06:09 UTC, Meltrust commented on src/components/indexes.js
> +const Indexes = () => {
- [x] According to the project requirements, you need to include a list of categories that could be filtered using given parameters, e.g. category name.  In your case, you could filter by company estate location, or even include a search box.

Look:

![image](https://user-images.githubusercontent.com/57421823/152479235-1d25f80c-aec0-434f-a4e9-e3efc0f11346.png)


That way, we will be moving closer to approval! 💪

2022-02-04 06:09 UTC, Meltrust commented on src/app/fetch.js
> +  .then((response) => response.json());
- [x] OPTIONAL: I suggest you filter the data from the API using a new filter component.

2022-02-04 06:09 UTC, Meltrust commented on src/App.js
> +import React, { useEffect } from 'react';
- [x] I couldn't find tests in your project.  According to the requirements:

![image](https://user-images.githubusercontent.com/57421823/152479746-892ab5c7-4035-42ee-9cce-faa536c8488d.png)

Therefore, kindly please add unit and integration tests, so we future-proof the app's functionality! 💪

2022-02-04 06:09 UTC, Meltrust commented on src/components/details.js
> +import { useEffect } from 'react';
- [ ] The details page is beautiful, however:

![image](https://user-images.githubusercontent.com/57421823/152480181-feb9eaab-5fd3-4157-9f1f-ccdb6251f3cb.png)

There seems a problem with your header horizontally overflowing the page.  Kindly fix it.

That way, we meet this requirement:

![image](https://user-images.githubusercontent.com/57421823/152480289-8b50d40f-0c94-47eb-9510-b63ea9a3deca.png)

... And your app will look beautiful and striking!! 💪

2022-02-04 17:45 UTC, MacCrazyman commented on src/app/fetch.js
> +  .then((response) => response.json());
Hello @Meltrust , thanks for the feedback, I'm already working on the changes suggested.
On the other hand, I want to get more clarity about this requirement. The file you are pointing to is not a react component, that file only contains the fetch functions to keep them organized, I would appreciate it if you can let me know what am I missing here or what do you want me to do in order to meet the requirement.
Regards.

2022-02-04 18:47 UTC, MacCrazyman commented on README.md
> +[Live Demo Link](https://stock-capstone.herokuapp.com/)
This one looks more like a problem in Heroku's service.
At the moment of publishing the PR and right now it is working for me.

![Capture](https://user-images.githubusercontent.com/87956045/152585507-7aa3ccbf-3849-4909-aa9b-5fca3b051fc1.PNG)
.

2022-02-04 21:33 UTC, Meltrust commented on src/app/fetch.js
> +  .then((response) => response.json());
Hello MacCrazyman, I'm looking at this inquiry.

2022-02-04 22:21 UTC, Meltrust commented on src/app/fetch.js
> +  .then((response) => response.json());
@MacCrazyman, I checked the project again at the point before my review.  You are very right, in this requirement made reference to the wrong file as a result of my own human mistake.  Thanks for pointing this out.

2022-02-05 05:17 UTC, Meltrust approved these changes
_Reviewed on Chrome_

Hi @MacCrazyman, 

## Congratulations!! Beautiful project!!!!

- [ ] OPTIONAL:  I approved this project because it works perfectly on Google Chrome.  However, the header/footer overflow is still there on Firefox.  Upon further examination, it seems to be the `grid` implementation, because when I deactivate it, the overflow corrects.  I highly suggest you resolve this issue when you have the time on Firefox because many tech recruiters are known to love that browser, and you don't want them to notice the overflow.  Congratulations on finishing React, good luck and happy coding!!

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-05 11:23 UTC, merged